#!/bin/bash

[ -n "$VERBOSE" ] && echo "postinst called with argument \`$1'" >&2
[ -n "$VERBOSE" ] && set -x

VERSION_SHORT=$(echo __VERSION__ | cut -d. -f1-3)

#
# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
#
case "$1" in
    configure)
      ln -sf __PREFIX__/drill/drill-${VERSION_SHORT} __PREFIX__/drill/current
      
      if [ -f __PREFIX__/drill/drillversion ]; then
        rm -f __PREFIX__/drill/drillversion
      fi
      echo "$VERSION_SHORT" > __PREFIX__/drill/drillversion

      OLD_DRILL_DIRS=`find "__PREFIX__/drill/" -maxdepth 1 -regex '.*drill-[0-9]*\.[0-9]*\.[0-9]*$' ! -name "*$VERSION_SHORT"`
      rm -rf ${OLD_DRILL_DIRS}
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


