#!/bin/bash

[ -n "$VERBOSE" ] && echo "postrm called with argument \`$1'" >&2
[ -n "$VERBOSE" ] && set -x

#
# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
#
case "$1" in
    upgrade)
    ;;

    remove|purge|disappear)
      VERSION_SHORT=$(echo __VERSION__ | cut -d. -f1-3)
      rm -f __PREFIX__/drill/current
      rm -Rf __PREFIX__/drill/drill-${VERSION_SHORT}
    ;;

    abort-install|abort-upgrade|failed-upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

