// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Types.proto
// Protobuf C++ Version: 4.25.5

#ifndef GOOGLE_PROTOBUF_INCLUDED_Types_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_Types_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025005 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Types_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Types_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Types_2eproto;
namespace common {
class MajorType;
struct MajorTypeDefaultTypeInternal;
extern MajorTypeDefaultTypeInternal _MajorType_default_instance_;
}  // namespace common
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace common {
enum MinorType : int {
  LATE = 0,
  MAP = 1,
  TINYINT = 3,
  SMALLINT = 4,
  INT = 5,
  BIGINT = 6,
  DECIMAL9 = 7,
  DECIMAL18 = 8,
  DECIMAL28SPARSE = 9,
  DECIMAL38SPARSE = 10,
  MONEY = 11,
  DATE = 12,
  TIME = 13,
  TIMETZ = 14,
  TIMESTAMPTZ = 15,
  TIMESTAMP = 16,
  INTERVAL = 17,
  FLOAT4 = 18,
  FLOAT8 = 19,
  BIT = 20,
  FIXEDCHAR = 21,
  FIXED16CHAR = 22,
  FIXEDBINARY = 23,
  VARCHAR = 24,
  VAR16CHAR = 25,
  VARBINARY = 26,
  UINT1 = 29,
  UINT2 = 30,
  UINT4 = 31,
  UINT8 = 32,
  DECIMAL28DENSE = 33,
  DECIMAL38DENSE = 34,
  DM_UNKNOWN = 37,
  INTERVALYEAR = 38,
  INTERVALDAY = 39,
  LIST = 40,
  GENERIC_OBJECT = 41,
  UNION = 42,
  VARDECIMAL = 43,
  DICT = 44,
};

bool MinorType_IsValid(int value);
extern const uint32_t MinorType_internal_data_[];
constexpr MinorType MinorType_MIN = static_cast<MinorType>(0);
constexpr MinorType MinorType_MAX = static_cast<MinorType>(44);
constexpr int MinorType_ARRAYSIZE = 44 + 1;
const ::google::protobuf::EnumDescriptor*
MinorType_descriptor();
template <typename T>
const std::string& MinorType_Name(T value) {
  static_assert(std::is_same<T, MinorType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to MinorType_Name().");
  return MinorType_Name(static_cast<MinorType>(value));
}
template <>
inline const std::string& MinorType_Name(MinorType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<MinorType_descriptor,
                                                 0, 44>(
      static_cast<int>(value));
}
inline bool MinorType_Parse(absl::string_view name, MinorType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MinorType>(
      MinorType_descriptor(), name, value);
}
enum DataMode : int {
  DM_OPTIONAL = 0,
  DM_REQUIRED = 1,
  DM_REPEATED = 2,
};

bool DataMode_IsValid(int value);
extern const uint32_t DataMode_internal_data_[];
constexpr DataMode DataMode_MIN = static_cast<DataMode>(0);
constexpr DataMode DataMode_MAX = static_cast<DataMode>(2);
constexpr int DataMode_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
DataMode_descriptor();
template <typename T>
const std::string& DataMode_Name(T value) {
  static_assert(std::is_same<T, DataMode>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to DataMode_Name().");
  return DataMode_Name(static_cast<DataMode>(value));
}
template <>
inline const std::string& DataMode_Name(DataMode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DataMode_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool DataMode_Parse(absl::string_view name, DataMode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DataMode>(
      DataMode_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class MajorType final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:common.MajorType) */ {
 public:
  inline MajorType() : MajorType(nullptr) {}
  ~MajorType() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR MajorType(::google::protobuf::internal::ConstantInitialized);

  inline MajorType(const MajorType& from)
      : MajorType(nullptr, from) {}
  MajorType(MajorType&& from) noexcept
    : MajorType() {
    *this = ::std::move(from);
  }

  inline MajorType& operator=(const MajorType& from) {
    CopyFrom(from);
    return *this;
  }
  inline MajorType& operator=(MajorType&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MajorType& default_instance() {
    return *internal_default_instance();
  }
  static inline const MajorType* internal_default_instance() {
    return reinterpret_cast<const MajorType*>(
               &_MajorType_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MajorType& a, MajorType& b) {
    a.Swap(&b);
  }
  inline void Swap(MajorType* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MajorType* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MajorType* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MajorType>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MajorType& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const MajorType& from) {
    MajorType::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(MajorType* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "common.MajorType";
  }
  protected:
  explicit MajorType(::google::protobuf::Arena* arena);
  MajorType(::google::protobuf::Arena* arena, const MajorType& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSubTypeFieldNumber = 7,
    kMinorTypeFieldNumber = 1,
    kModeFieldNumber = 2,
    kWidthFieldNumber = 3,
    kPrecisionFieldNumber = 4,
    kScaleFieldNumber = 5,
    kTimeZoneFieldNumber = 6,
  };
  // repeated .common.MinorType sub_type = 7;
  int sub_type_size() const;
  private:
  int _internal_sub_type_size() const;

  public:
  void clear_sub_type() ;
  public:
  ::common::MinorType sub_type(int index) const;
  void set_sub_type(int index, ::common::MinorType value);
  void add_sub_type(::common::MinorType value);
  const ::google::protobuf::RepeatedField<int>& sub_type() const;
  ::google::protobuf::RepeatedField<int>* mutable_sub_type();

  private:
  const ::google::protobuf::RepeatedField<int>& _internal_sub_type() const;
  ::google::protobuf::RepeatedField<int>* _internal_mutable_sub_type();

  public:
  // optional .common.MinorType minor_type = 1;
  bool has_minor_type() const;
  void clear_minor_type() ;
  ::common::MinorType minor_type() const;
  void set_minor_type(::common::MinorType value);

  private:
  ::common::MinorType _internal_minor_type() const;
  void _internal_set_minor_type(::common::MinorType value);

  public:
  // optional .common.DataMode mode = 2;
  bool has_mode() const;
  void clear_mode() ;
  ::common::DataMode mode() const;
  void set_mode(::common::DataMode value);

  private:
  ::common::DataMode _internal_mode() const;
  void _internal_set_mode(::common::DataMode value);

  public:
  // optional int32 width = 3;
  bool has_width() const;
  void clear_width() ;
  ::int32_t width() const;
  void set_width(::int32_t value);

  private:
  ::int32_t _internal_width() const;
  void _internal_set_width(::int32_t value);

  public:
  // optional int32 precision = 4;
  bool has_precision() const;
  void clear_precision() ;
  ::int32_t precision() const;
  void set_precision(::int32_t value);

  private:
  ::int32_t _internal_precision() const;
  void _internal_set_precision(::int32_t value);

  public:
  // optional int32 scale = 5;
  bool has_scale() const;
  void clear_scale() ;
  ::int32_t scale() const;
  void set_scale(::int32_t value);

  private:
  ::int32_t _internal_scale() const;
  void _internal_set_scale(::int32_t value);

  public:
  // optional int32 timeZone = 6;
  bool has_timezone() const;
  void clear_timezone() ;
  ::int32_t timezone() const;
  void set_timezone(::int32_t value);

  private:
  ::int32_t _internal_timezone() const;
  void _internal_set_timezone(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:common.MajorType)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 3,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<int> sub_type_;
    int minor_type_;
    int mode_;
    ::int32_t width_;
    ::int32_t precision_;
    ::int32_t scale_;
    ::int32_t timezone_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Types_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MajorType

// optional .common.MinorType minor_type = 1;
inline bool MajorType::has_minor_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void MajorType::clear_minor_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.minor_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::common::MinorType MajorType::minor_type() const {
  // @@protoc_insertion_point(field_get:common.MajorType.minor_type)
  return _internal_minor_type();
}
inline void MajorType::set_minor_type(::common::MinorType value) {
  _internal_set_minor_type(value);
  // @@protoc_insertion_point(field_set:common.MajorType.minor_type)
}
inline ::common::MinorType MajorType::_internal_minor_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::common::MinorType>(_impl_.minor_type_);
}
inline void MajorType::_internal_set_minor_type(::common::MinorType value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  assert(::common::MinorType_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.minor_type_ = value;
}

// optional .common.DataMode mode = 2;
inline bool MajorType::has_mode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void MajorType::clear_mode() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.mode_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::common::DataMode MajorType::mode() const {
  // @@protoc_insertion_point(field_get:common.MajorType.mode)
  return _internal_mode();
}
inline void MajorType::set_mode(::common::DataMode value) {
  _internal_set_mode(value);
  // @@protoc_insertion_point(field_set:common.MajorType.mode)
}
inline ::common::DataMode MajorType::_internal_mode() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::common::DataMode>(_impl_.mode_);
}
inline void MajorType::_internal_set_mode(::common::DataMode value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  assert(::common::DataMode_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.mode_ = value;
}

// optional int32 width = 3;
inline bool MajorType::has_width() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void MajorType::clear_width() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.width_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t MajorType::width() const {
  // @@protoc_insertion_point(field_get:common.MajorType.width)
  return _internal_width();
}
inline void MajorType::set_width(::int32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:common.MajorType.width)
}
inline ::int32_t MajorType::_internal_width() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.width_;
}
inline void MajorType::_internal_set_width(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.width_ = value;
}

// optional int32 precision = 4;
inline bool MajorType::has_precision() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void MajorType::clear_precision() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.precision_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t MajorType::precision() const {
  // @@protoc_insertion_point(field_get:common.MajorType.precision)
  return _internal_precision();
}
inline void MajorType::set_precision(::int32_t value) {
  _internal_set_precision(value);
  // @@protoc_insertion_point(field_set:common.MajorType.precision)
}
inline ::int32_t MajorType::_internal_precision() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.precision_;
}
inline void MajorType::_internal_set_precision(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.precision_ = value;
}

// optional int32 scale = 5;
inline bool MajorType::has_scale() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void MajorType::clear_scale() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.scale_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t MajorType::scale() const {
  // @@protoc_insertion_point(field_get:common.MajorType.scale)
  return _internal_scale();
}
inline void MajorType::set_scale(::int32_t value) {
  _internal_set_scale(value);
  // @@protoc_insertion_point(field_set:common.MajorType.scale)
}
inline ::int32_t MajorType::_internal_scale() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.scale_;
}
inline void MajorType::_internal_set_scale(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.scale_ = value;
}

// optional int32 timeZone = 6;
inline bool MajorType::has_timezone() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void MajorType::clear_timezone() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.timezone_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int32_t MajorType::timezone() const {
  // @@protoc_insertion_point(field_get:common.MajorType.timeZone)
  return _internal_timezone();
}
inline void MajorType::set_timezone(::int32_t value) {
  _internal_set_timezone(value);
  // @@protoc_insertion_point(field_set:common.MajorType.timeZone)
}
inline ::int32_t MajorType::_internal_timezone() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.timezone_;
}
inline void MajorType::_internal_set_timezone(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.timezone_ = value;
}

// repeated .common.MinorType sub_type = 7;
inline int MajorType::_internal_sub_type_size() const {
  return _internal_sub_type().size();
}
inline int MajorType::sub_type_size() const {
  return _internal_sub_type_size();
}
inline void MajorType::clear_sub_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.sub_type_.Clear();
}
inline ::common::MinorType MajorType::sub_type(int index) const {
  // @@protoc_insertion_point(field_get:common.MajorType.sub_type)
  return static_cast<::common::MinorType>(_internal_sub_type().Get(index));
}
inline void MajorType::set_sub_type(int index, ::common::MinorType value) {
  assert(::common::MinorType_IsValid(value));
  _internal_mutable_sub_type()->Set(index, value);
  // @@protoc_insertion_point(field_set:common.MajorType.sub_type)
}
inline void MajorType::add_sub_type(::common::MinorType value) {
  assert(::common::MinorType_IsValid(value));
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_sub_type()->Add(value);
  // @@protoc_insertion_point(field_add:common.MajorType.sub_type)
}
inline const ::google::protobuf::RepeatedField<int>& MajorType::sub_type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:common.MajorType.sub_type)
  return _internal_sub_type();
}
inline ::google::protobuf::RepeatedField<int>* MajorType::mutable_sub_type()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:common.MajorType.sub_type)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_sub_type();
}
inline const ::google::protobuf::RepeatedField<int>& MajorType::_internal_sub_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.sub_type_;
}
inline ::google::protobuf::RepeatedField<int>* MajorType::_internal_mutable_sub_type() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.sub_type_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace common


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::common::MinorType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::common::MinorType>() {
  return ::common::MinorType_descriptor();
}
template <>
struct is_proto_enum<::common::DataMode> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::common::DataMode>() {
  return ::common::DataMode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_Types_2eproto_2epb_2eh
