// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecutionProtos.proto
// Protobuf C++ Version: 4.25.5

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExecutionProtos_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExecutionProtos_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025005 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "Coordination.pb.h"
#include "UserBitShared.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExecutionProtos_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ExecutionProtos_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ExecutionProtos_2eproto;
namespace exec {
namespace bit {
class FragmentHandle;
struct FragmentHandleDefaultTypeInternal;
extern FragmentHandleDefaultTypeInternal _FragmentHandle_default_instance_;
class ServerPreparedStatementState;
struct ServerPreparedStatementStateDefaultTypeInternal;
extern ServerPreparedStatementStateDefaultTypeInternal _ServerPreparedStatementState_default_instance_;
}  // namespace bit
}  // namespace exec
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace exec {
namespace bit {

// ===================================================================


// -------------------------------------------------------------------

class ServerPreparedStatementState final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:exec.bit.ServerPreparedStatementState) */ {
 public:
  inline ServerPreparedStatementState() : ServerPreparedStatementState(nullptr) {}
  ~ServerPreparedStatementState() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ServerPreparedStatementState(::google::protobuf::internal::ConstantInitialized);

  inline ServerPreparedStatementState(const ServerPreparedStatementState& from)
      : ServerPreparedStatementState(nullptr, from) {}
  ServerPreparedStatementState(ServerPreparedStatementState&& from) noexcept
    : ServerPreparedStatementState() {
    *this = ::std::move(from);
  }

  inline ServerPreparedStatementState& operator=(const ServerPreparedStatementState& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerPreparedStatementState& operator=(ServerPreparedStatementState&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServerPreparedStatementState& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerPreparedStatementState* internal_default_instance() {
    return reinterpret_cast<const ServerPreparedStatementState*>(
               &_ServerPreparedStatementState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ServerPreparedStatementState& a, ServerPreparedStatementState& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerPreparedStatementState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerPreparedStatementState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServerPreparedStatementState* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ServerPreparedStatementState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ServerPreparedStatementState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ServerPreparedStatementState& from) {
    ServerPreparedStatementState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ServerPreparedStatementState* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "exec.bit.ServerPreparedStatementState";
  }
  protected:
  explicit ServerPreparedStatementState(::google::protobuf::Arena* arena);
  ServerPreparedStatementState(::google::protobuf::Arena* arena, const ServerPreparedStatementState& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSqlQueryFieldNumber = 1,
  };
  // optional string sql_query = 1;
  bool has_sql_query() const;
  void clear_sql_query() ;
  const std::string& sql_query() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sql_query(Arg_&& arg, Args_... args);
  std::string* mutable_sql_query();
  PROTOBUF_NODISCARD std::string* release_sql_query();
  void set_allocated_sql_query(std::string* value);

  private:
  const std::string& _internal_sql_query() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sql_query(
      const std::string& value);
  std::string* _internal_mutable_sql_query();

  public:
  // @@protoc_insertion_point(class_scope:exec.bit.ServerPreparedStatementState)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      55, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr sql_query_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ExecutionProtos_2eproto;
};// -------------------------------------------------------------------

class FragmentHandle final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:exec.bit.FragmentHandle) */ {
 public:
  inline FragmentHandle() : FragmentHandle(nullptr) {}
  ~FragmentHandle() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR FragmentHandle(::google::protobuf::internal::ConstantInitialized);

  inline FragmentHandle(const FragmentHandle& from)
      : FragmentHandle(nullptr, from) {}
  FragmentHandle(FragmentHandle&& from) noexcept
    : FragmentHandle() {
    *this = ::std::move(from);
  }

  inline FragmentHandle& operator=(const FragmentHandle& from) {
    CopyFrom(from);
    return *this;
  }
  inline FragmentHandle& operator=(FragmentHandle&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FragmentHandle& default_instance() {
    return *internal_default_instance();
  }
  static inline const FragmentHandle* internal_default_instance() {
    return reinterpret_cast<const FragmentHandle*>(
               &_FragmentHandle_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FragmentHandle& a, FragmentHandle& b) {
    a.Swap(&b);
  }
  inline void Swap(FragmentHandle* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FragmentHandle* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FragmentHandle* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FragmentHandle>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FragmentHandle& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const FragmentHandle& from) {
    FragmentHandle::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(FragmentHandle* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "exec.bit.FragmentHandle";
  }
  protected:
  explicit FragmentHandle(::google::protobuf::Arena* arena);
  FragmentHandle(::google::protobuf::Arena* arena, const FragmentHandle& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQueryIdFieldNumber = 1,
    kParentQueryIdFieldNumber = 4,
    kMajorFragmentIdFieldNumber = 2,
    kMinorFragmentIdFieldNumber = 3,
  };
  // optional .exec.shared.QueryId query_id = 1;
  bool has_query_id() const;
  void clear_query_id() ;
  const ::exec::shared::QueryId& query_id() const;
  PROTOBUF_NODISCARD ::exec::shared::QueryId* release_query_id();
  ::exec::shared::QueryId* mutable_query_id();
  void set_allocated_query_id(::exec::shared::QueryId* value);
  void unsafe_arena_set_allocated_query_id(::exec::shared::QueryId* value);
  ::exec::shared::QueryId* unsafe_arena_release_query_id();

  private:
  const ::exec::shared::QueryId& _internal_query_id() const;
  ::exec::shared::QueryId* _internal_mutable_query_id();

  public:
  // optional .exec.shared.QueryId parent_query_id = 4;
  bool has_parent_query_id() const;
  void clear_parent_query_id() ;
  const ::exec::shared::QueryId& parent_query_id() const;
  PROTOBUF_NODISCARD ::exec::shared::QueryId* release_parent_query_id();
  ::exec::shared::QueryId* mutable_parent_query_id();
  void set_allocated_parent_query_id(::exec::shared::QueryId* value);
  void unsafe_arena_set_allocated_parent_query_id(::exec::shared::QueryId* value);
  ::exec::shared::QueryId* unsafe_arena_release_parent_query_id();

  private:
  const ::exec::shared::QueryId& _internal_parent_query_id() const;
  ::exec::shared::QueryId* _internal_mutable_parent_query_id();

  public:
  // optional int32 major_fragment_id = 2;
  bool has_major_fragment_id() const;
  void clear_major_fragment_id() ;
  ::int32_t major_fragment_id() const;
  void set_major_fragment_id(::int32_t value);

  private:
  ::int32_t _internal_major_fragment_id() const;
  void _internal_set_major_fragment_id(::int32_t value);

  public:
  // optional int32 minor_fragment_id = 3;
  bool has_minor_fragment_id() const;
  void clear_minor_fragment_id() ;
  ::int32_t minor_fragment_id() const;
  void set_minor_fragment_id(::int32_t value);

  private:
  ::int32_t _internal_minor_fragment_id() const;
  void _internal_set_minor_fragment_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:exec.bit.FragmentHandle)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 2,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::exec::shared::QueryId* query_id_;
    ::exec::shared::QueryId* parent_query_id_;
    ::int32_t major_fragment_id_;
    ::int32_t minor_fragment_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ExecutionProtos_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// FragmentHandle

// optional .exec.shared.QueryId query_id = 1;
inline bool FragmentHandle::has_query_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.query_id_ != nullptr);
  return value;
}
inline const ::exec::shared::QueryId& FragmentHandle::_internal_query_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::exec::shared::QueryId* p = _impl_.query_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::exec::shared::QueryId&>(::exec::shared::_QueryId_default_instance_);
}
inline const ::exec::shared::QueryId& FragmentHandle::query_id() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:exec.bit.FragmentHandle.query_id)
  return _internal_query_id();
}
inline void FragmentHandle::unsafe_arena_set_allocated_query_id(::exec::shared::QueryId* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.query_id_);
  }
  _impl_.query_id_ = reinterpret_cast<::exec::shared::QueryId*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:exec.bit.FragmentHandle.query_id)
}
inline ::exec::shared::QueryId* FragmentHandle::release_query_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::exec::shared::QueryId* released = _impl_.query_id_;
  _impl_.query_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::exec::shared::QueryId* FragmentHandle::unsafe_arena_release_query_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:exec.bit.FragmentHandle.query_id)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::exec::shared::QueryId* temp = _impl_.query_id_;
  _impl_.query_id_ = nullptr;
  return temp;
}
inline ::exec::shared::QueryId* FragmentHandle::_internal_mutable_query_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.query_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::exec::shared::QueryId>(GetArena());
    _impl_.query_id_ = reinterpret_cast<::exec::shared::QueryId*>(p);
  }
  return _impl_.query_id_;
}
inline ::exec::shared::QueryId* FragmentHandle::mutable_query_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::exec::shared::QueryId* _msg = _internal_mutable_query_id();
  // @@protoc_insertion_point(field_mutable:exec.bit.FragmentHandle.query_id)
  return _msg;
}
inline void FragmentHandle::set_allocated_query_id(::exec::shared::QueryId* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.query_id_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.query_id_ = reinterpret_cast<::exec::shared::QueryId*>(value);
  // @@protoc_insertion_point(field_set_allocated:exec.bit.FragmentHandle.query_id)
}

// optional int32 major_fragment_id = 2;
inline bool FragmentHandle::has_major_fragment_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void FragmentHandle::clear_major_fragment_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.major_fragment_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t FragmentHandle::major_fragment_id() const {
  // @@protoc_insertion_point(field_get:exec.bit.FragmentHandle.major_fragment_id)
  return _internal_major_fragment_id();
}
inline void FragmentHandle::set_major_fragment_id(::int32_t value) {
  _internal_set_major_fragment_id(value);
  // @@protoc_insertion_point(field_set:exec.bit.FragmentHandle.major_fragment_id)
}
inline ::int32_t FragmentHandle::_internal_major_fragment_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.major_fragment_id_;
}
inline void FragmentHandle::_internal_set_major_fragment_id(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.major_fragment_id_ = value;
}

// optional int32 minor_fragment_id = 3;
inline bool FragmentHandle::has_minor_fragment_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void FragmentHandle::clear_minor_fragment_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.minor_fragment_id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t FragmentHandle::minor_fragment_id() const {
  // @@protoc_insertion_point(field_get:exec.bit.FragmentHandle.minor_fragment_id)
  return _internal_minor_fragment_id();
}
inline void FragmentHandle::set_minor_fragment_id(::int32_t value) {
  _internal_set_minor_fragment_id(value);
  // @@protoc_insertion_point(field_set:exec.bit.FragmentHandle.minor_fragment_id)
}
inline ::int32_t FragmentHandle::_internal_minor_fragment_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.minor_fragment_id_;
}
inline void FragmentHandle::_internal_set_minor_fragment_id(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.minor_fragment_id_ = value;
}

// optional .exec.shared.QueryId parent_query_id = 4;
inline bool FragmentHandle::has_parent_query_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.parent_query_id_ != nullptr);
  return value;
}
inline const ::exec::shared::QueryId& FragmentHandle::_internal_parent_query_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::exec::shared::QueryId* p = _impl_.parent_query_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::exec::shared::QueryId&>(::exec::shared::_QueryId_default_instance_);
}
inline const ::exec::shared::QueryId& FragmentHandle::parent_query_id() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:exec.bit.FragmentHandle.parent_query_id)
  return _internal_parent_query_id();
}
inline void FragmentHandle::unsafe_arena_set_allocated_parent_query_id(::exec::shared::QueryId* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.parent_query_id_);
  }
  _impl_.parent_query_id_ = reinterpret_cast<::exec::shared::QueryId*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:exec.bit.FragmentHandle.parent_query_id)
}
inline ::exec::shared::QueryId* FragmentHandle::release_parent_query_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::exec::shared::QueryId* released = _impl_.parent_query_id_;
  _impl_.parent_query_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::exec::shared::QueryId* FragmentHandle::unsafe_arena_release_parent_query_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:exec.bit.FragmentHandle.parent_query_id)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::exec::shared::QueryId* temp = _impl_.parent_query_id_;
  _impl_.parent_query_id_ = nullptr;
  return temp;
}
inline ::exec::shared::QueryId* FragmentHandle::_internal_mutable_parent_query_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.parent_query_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::exec::shared::QueryId>(GetArena());
    _impl_.parent_query_id_ = reinterpret_cast<::exec::shared::QueryId*>(p);
  }
  return _impl_.parent_query_id_;
}
inline ::exec::shared::QueryId* FragmentHandle::mutable_parent_query_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::exec::shared::QueryId* _msg = _internal_mutable_parent_query_id();
  // @@protoc_insertion_point(field_mutable:exec.bit.FragmentHandle.parent_query_id)
  return _msg;
}
inline void FragmentHandle::set_allocated_parent_query_id(::exec::shared::QueryId* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.parent_query_id_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.parent_query_id_ = reinterpret_cast<::exec::shared::QueryId*>(value);
  // @@protoc_insertion_point(field_set_allocated:exec.bit.FragmentHandle.parent_query_id)
}

// -------------------------------------------------------------------

// ServerPreparedStatementState

// optional string sql_query = 1;
inline bool ServerPreparedStatementState::has_sql_query() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ServerPreparedStatementState::clear_sql_query() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.sql_query_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ServerPreparedStatementState::sql_query() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:exec.bit.ServerPreparedStatementState.sql_query)
  return _internal_sql_query();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ServerPreparedStatementState::set_sql_query(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.sql_query_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:exec.bit.ServerPreparedStatementState.sql_query)
}
inline std::string* ServerPreparedStatementState::mutable_sql_query() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sql_query();
  // @@protoc_insertion_point(field_mutable:exec.bit.ServerPreparedStatementState.sql_query)
  return _s;
}
inline const std::string& ServerPreparedStatementState::_internal_sql_query() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.sql_query_.Get();
}
inline void ServerPreparedStatementState::_internal_set_sql_query(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.sql_query_.Set(value, GetArena());
}
inline std::string* ServerPreparedStatementState::_internal_mutable_sql_query() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.sql_query_.Mutable( GetArena());
}
inline std::string* ServerPreparedStatementState::release_sql_query() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:exec.bit.ServerPreparedStatementState.sql_query)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.sql_query_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sql_query_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ServerPreparedStatementState::set_allocated_sql_query(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.sql_query_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.sql_query_.IsDefault()) {
          _impl_.sql_query_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:exec.bit.ServerPreparedStatementState.sql_query)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace bit
}  // namespace exec


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExecutionProtos_2eproto_2epb_2eh
