#!/bin/bash

[ -n "$VERBOSE" ] && echo "postinst called with argument \`$1'" >&2
[ -n "$VERBOSE" ] && set -x

VERSION_SHORT=$(echo __VERSION__ | cut -d. -f1-3)

#
# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
#
case "$1" in
    configure)
      echo "$VERSION_SHORT" > __PREFIX__/drill/drillversion

      #
      # change ownership
      #
      DAEMON_CONF="__PREFIX__/conf/daemon.conf"

      if [ -f "$DAEMON_CONF" ]; then
          MAPR_USER=$( awk -F = '$1 == "mapr.daemon.user" { print $2 }' $DAEMON_CONF)

          if [ ! -z "$MAPR_USER" ]; then
              chown -R $MAPR_USER __PREFIX__/drill/drill-${VERSION_SHORT}
          fi
      fi

      chmod 1777 -R __PREFIX__/drill/drill-${VERSION_SHORT}/logs
      touch __PREFIX__/drill/drill-${VERSION_SHORT}/logs/sqlline.log
      chmod 666 __PREFIX__/drill/drill-${VERSION_SHORT}/logs/sqlline.log

      # distrib-env.sh is replaced at build time - no longer a need to generate its contents at install time

      if [ ! -f /opt/mapr/conf/mapr.login.conf ]; then
          cp -f __PREFIX__/drill/drill-${VERSION_SHORT}/conf/mapr.login.conf /opt/mapr/conf/.
      fi
      if [ -f __INSTALL_3DIGIT__/conf/mapr.login.conf ]; then
        rm -f __INSTALL_3DIGIT__/conf/mapr.login.conf
      fi

      ln -sf __PREFIX__/drill/drill-${VERSION_SHORT}/bin/sqlline /usr/bin/sqlline

      #
      # get ZK list and cluster ID for drill-override.conf
      #
      drillOverrideConf="__PREFIX__/drill/drill-${VERSION_SHORT}/conf/drill-override.conf"
      oldClusterId="drillbits1"
      oldZkConnect="localhost:2181"

      isZkAddressDiscovered=0
      zkLine=$(grep zookeeper.servers /opt/mapr/conf/warden.conf)
      if [ -n "$zkLine" ]; then
        zkServers=$(echo $zkLine | sed 's/zookeeper.servers=//' | tr ' ' ',')
        isZkAddressDiscovered=1
      fi

      if [ "${isZkAddressDiscovered}" = "1" ]; then
        sed -i -e "s/$oldZkConnect/$zkServers/g" $drillOverrideConf
      else
        echo "Could not detect Zookeeper information"
        echo "Not found zookeeper.servers in file /opt/mapr/conf/warden.conf"
        echo "Once you configure this MapR node to connect to Zookeeper, then you need to edit ${drillOverrideConf}"
      fi

      if [ -f __PREFIX__/conf/mapr-clusters.conf ]; then
        clusters=`cat __PREFIX__/conf/mapr-clusters.conf`
        clusterName=`echo ${clusters} | awk '{print $1;}'`
        clusterName=`echo ${clusterName//./_}`
        clusterName=`echo ${clusterName// /_}`
        newClusterId="${clusterName}-drillbits"
      else
        echo "Did not detect file /opt/mapr/conf/mapr-clusters.conf"
        echo "Drillbit cluster name will default to 'default-drillbit-cluster-name-drillbits'"
        newClusterId="default-drillbit-cluster-name-drillbits"
      fi
      sed -i -e "s/$oldClusterId/$newClusterId/g" $drillOverrideConf

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


