# Drill-on-YARN configuration.
# See drill-on-yarn-example.conf for the complete set
# of configuration options.

drill.yarn: {
  drill-install: {
    # MapR ships the Drill archive within $DRILL_HOME.
    client-path: "drill.tar.gz"
  }
  dfs: {
    # Default DFS upload location. Change to suite your needs.

    # app-dir: "/user/drill"
  }
  drillbit: {
    # Settings for a very small Drillbit. Normal Drill defaults are 8G
    # for direct memory. This size is chosen so that Drill will run under
    # a default YARN installation that limits containers to 8G. You will
    # want to increase these values, but first you will have to change the
    # YARN maximum container size. See the documentation.
    heap:  "3G"
    max-direct-memory: "3G"
    code-cache: "1G"
    # Container memory: heap + max-direct-memory + code-cache + 1 GB JVM overhead
    memory-mb: 8192

    #heap: "4G"
    #max-direct-memory: "8G"
    #code-cache: "1G"
    # Container memory: heap + max-direct-memory + code-cache + 1 GB JVM overhead
    #memory-mb: 14336

    # Settings for a very minimal container. Change these to better fit your
    # actual hardware and needs.
    # Note: Disks is a setting specific to MapR.
    # Note: YARN does not enforce vcores usage; set this value based on
    # observation of what your Drillbit actually uses under a typical load.

    vcores: 2
    disks: 1
  }
  cluster: [
    {
      # Arbitrary name, just used for error and statistics reporting.

      name: "drillbits"

      # Basic tier: let YARN pick any available node.
      # Production systems will want to use a labeled queue.
      # See documentation for details.

      type: "basic"

      # Number of Drill-bits to run. (Drill-on-YARN runs each on a separate host,
      # so this is also the number of hosts that will run Drill.)

      count: 1
    }
  ]
}
